### ISSUE TITLE
VPP issues

### ISSUE THREAD

**Issue by quamt** [rigaya/VCEEnc#28] opened 2021-06-18 12:25 UTC
When I for example use
vpp-resize and trybto upscale from 640x480 to
-2x720 or - 2x1080 with a RX 570, the encoding starts but it stops after a few %. 
I tried to create a log file for errors but nothing is inside.

Which logfile is recommended to create for this case? 

Attached debug log
[test-log.zip](https://github.com/rigaya/VCEEnc/files/6679764/test-log.zip)

**Comment by quamt** [comment] 2021-06-22 03:04
@rigaya 
Anything that can be seen as where the issue is coming from?

**Comment by rigaya** [comment] 2021-06-28 12:40
I'm unable to reproduce the issue, but recent drivers seems to have trouble with VCE. There are reports that [21.4.1](https://github.com/obsproject/obs-studio/issues/4689) and 21.6.1 are unstable.

I'm currently using 21.2.2 which seems to be fine.

**Comment by quamt** [comment] 2021-06-28 12:41
Ill try to downgrade the driver and let you know.

**Comment by quamt** [comment] 2021-06-29 05:17
Ok installed 21.2.2 with factory reset the driver and no problem now.
Since its a driver issue do you want to close it?

**Comment by rigaya** [comment] 2021-06-29 14:11
Nice to hear it works fine with 21.2.2.

I'll close this issue as this seems to be a driver issue.

**Closed by rigaya** 2021-06-29 14:11 UTC
